# Main Travis CI configuration file for wordpress-plugin tests
# https://github.com/benbalter/wordpress-plugin-tests

# Tell Travis CI we're using PHP
language: php
 
sudo: false
 
php:
  - 7.0
  - 7.1
 
script:
  # Run your tests here.
  - echo 'Tested'