sudo: false
dist: trusty

language: php
php: 7.2

branches:
  only:
    - master

before_script:
  - composer require squizlabs/php_codesniffer
  - phpenv rehash
  - phpcs -i
  - phpenv rehash
  - phpcs --config-set installed_paths $(pear config-get php_dir)/PHP/CodeSniffer/Standards
  - phpcs --config-set error_severity 0
  - phpcs --config-set warning_severity 0

jobs:
  include:
    - stage: sniff
      script:
        - phpcs .
      env: BUILD=sniff
    - stage: test
      php: 7.3
      env: WP_VERSION=latest
    - stage: test
      php: 7.2
      env: WP_VERSION=latest
    - stage: test
      php: 7.1
      env: WP_VERSION=latest
    - stage: test
      php: 7.0
      env: WP_VERSION=latest
    - stage: test
      php: 5.6
      env: WP_VERSION=latest
    - stage: test
      php: 5.6
      env: WP_VERSION=3.7.11
    - stage: test
      php: 5.6
      env: WP_VERSION=trunk
    - stage: test
      php: 5.4
      dist: precise
env: WP_VERSION=5.1